Repository cvxpy/cvxpy, pull requests merged in 2022-11, with the labels that each got.

#1931 SciPy 1.9 compatibility
  cvxpy/atoms/elementwise/elementwise.py
Labels: backport bugfix to 1.1 and 1.2

#1840 WIP: New SciPy backend
  .github/workflows/test_backends.yml
  cvxpy/__init__.py
  cvxpy/cvxcore/python/canonInterface.py
  cvxpy/lin_ops/canon_backend.py
  cvxpy/problems/problem.py
  cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
  cvxpy/reductions/qp2quad_form/qp_matrix_stuffing.py
  cvxpy/reductions/solvers/solving_chain.py
  cvxpy/settings.py
  cvxpy/tests/test_python_backends.py
  cvxpy/utilities/coeff_extractor.py
  doc/source/index.rst
  doc/source/tutorial/advanced/index.rst
Labels: canonicalization

#1951 Pin setuptools version to fix installation with pip
  pyproject.toml
  setup.cfg
  setup.py
Labels: backport bugfix to 1.2, next patch

#1962 Adapt to API changes in gurobipy
  cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py
  cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
Labels: backport bugfix to 1.1 and 1.2, next patch
