Repository cvxpy/cvxpy, pull requests merged in 2022-08, with the labels that each got.

#1874 [CI] Fix dependency installation
  continuous_integration/install_dependencies.sh
  continuous_integration/test_script.sh
Labels: CI

#1852 Allow deecopy of constraints
  cvxpy/tests/test_problem.py
  cvxpy/utilities/canonical.py
  cvxpy/utilities/deterministic.py
Labels: backport bugfix to 1.1 and 1.2

#1880 Switch SCS timings to seconds
  cvxpy/reductions/solvers/conic_solvers/scs_conif.py
Labels: Interface: SCS, backport bugfix to 1.1 and 1.2

#1882 fix osqp warm start
  cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py
Labels: backport bugfix to 1.1 and 1.2

#1885 Fix tests that started failing with Mosek 10
  cvxpy/tests/solver_test_helpers.py
  cvxpy/tests/test_conic_solvers.py
Labels: backport bugfix to 1.1 and 1.2

#1887 [CI] Bump Ubuntu runner
  .github/workflows/build.yml
Labels: CI
