Repository cvxpy/cvxpy, pull requests merged in 2023-05, with the labels that each got.

#2118 `setup.py`: Remove `setup_requires`, remove setuptools from `install_requires'
  setup.py
Labels: backport bugfix to 1.2 and 1.3

#2123 Correct categorization of ``tr_inv`` atom.
  cvxpy/atoms/__init__.py
Labels: backport bugfix to 1.3

#2133 Map imprecise status of COPT to optimal_inaccurate of CVXPY
  cvxpy/reductions/solvers/conic_solvers/copt_conif.py
  cvxpy/reductions/solvers/qp_solvers/copt_qpif.py
Labels: backport bugfix to 1.3

#2086 Fix rare bugs in curvature calculation: identity matrices and nondeterministic starting vectors in eigsh
  cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py
  cvxpy/utilities/linalg.py
Labels: backport bugfix to 1.1; 1.2; 1.3

#2134 Map imprecise status of COPT to optimal_inaccurate status of CVXPY
  cvxpy/reductions/solvers/conic_solvers/copt_conif.py
  cvxpy/reductions/solvers/qp_solvers/copt_qpif.py
Labels: backport bugfix to 1.1; 1.2; 1.3

#2127 Follow-up Mosek accept unknown
  cvxpy/tests/test_conic_solvers.py
Labels: Interface: MOSEK

#2126 Fix bug with calling Mosek simplex solver
  cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
  cvxpy/tests/test_conic_solvers.py
Labels: backport bugfix to 1.1; 1.2; 1.3
