Repository cvxpy/cvxpy, pull requests merged in 2024-04, with the labels that each got.

#2406 [Bug] Parametrized quad form broken when values are zero
  cvxpy/lin_ops/canon_backend.py
  cvxpy/tests/test_coeff_extractor.py
  cvxpy/tests/test_python_backends.py
  cvxpy/utilities/coeff_extractor.py
Labels: bug, backport to 1.4

#2412 [Doc] Adds GitHub release description to PROCEDURES
  PROCEDURES.md
Labels: documentation

#2420 Preserve expression sign in canonicalization of minimum and maximum
  cvxpy/reductions/eliminate_pwl/canonicalizers/maximum_canon.py
  cvxpy/tests/test_canon_sign.py
Labels: bug, backport to 1.4

#2425 Fixes XPRESS interface
  cvxpy/reductions/solvers/conic_solvers/xpress_conif.py
Labels: Interface: XPRESS
