Repository cvxpy/cvxpy, pull requests merged in 2024-11, with the labels that each got.

#2616 CI: avoid installing pyscipopt and cylp for all python versions
  continuous_integration/install_dependencies.sh
Labels: PR backport needed

#2582 DOC: adding new features in docs for 1.6
  doc/source/index.rst
  doc/source/tutorial/advanced/index.rst
  doc/source/tutorial/constraints/index.rst
  doc/source/tutorial/intro/index.rst
  doc/source/updates/index.rst
Labels: documentation, PR no backport needed

#2606 `quantum_rel_entr`, `quantum_cond_entr` && CVXPY QI Marimo demo
  cvxpy/atoms/__init__.py
  cvxpy/atoms/quantum_cond_entr.py
  cvxpy/atoms/quantum_rel_entr.py
  cvxpy/reductions/complex2real/canonicalizers/__init__.py
  cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py
  cvxpy/reductions/dcp2cone/canonicalizers/__init__.py
  cvxpy/reductions/dcp2cone/canonicalizers/quantum_rel_entr_canon.py
  cvxpy/tests/test_quantum_rel_entr.py
  cvxpy/tests/test_von_neumann_entr.py
  examples/QI_demo.py
Labels: PR no backport needed

#2624 Fixes diffcp imports
  cvxpy/reductions/solvers/conic_solvers/diffcp_conif.py
Labels: PR backport needed

#2630 Fix breaking tests due to gurobi interface update
  cvxpy/tests/test_conic_solvers.py
  cvxpy/tests/test_qp_solvers.py
Labels: PR backport needed
