Repository cvxpy/cvxpy, pull requests merged in 2024-10, with the labels that each got.

#2532 Sparsity attribute
  cvxpy/expressions/leaf.py
  cvxpy/problems/problem.py
  cvxpy/reductions/cvx_attr2constr.py
  cvxpy/tests/test_attributes.py
Labels: PR no backport needed

#2579 support for ND reshape
  cvxpy/atoms/affine/reshape.py
  cvxpy/atoms/affine/transpose.py
  cvxpy/lin_ops/lin_utils.py
  cvxpy/tests/test_expressions.py
Labels: PR no backport needed

#2578 Nit: Indent and formatting updates for docs
  doc/source/contributing/index.rst
  doc/source/install/index.rst
  doc/source/resources/license/index.rst
  doc/source/tutorial/constraints/index.rst
  doc/source/tutorial/functions/index.rst
  doc/source/tutorial/solvers/index.rst
  doc/source/updates/index.rst
Labels: documentation, PR no backport needed

#2581 CI: Refactoring installation of dependencies
  continuous_integration/install_dependencies.sh
Labels: CI, PR no backport needed

#2586 Updating link to NAG website in documentation
  doc/source/tutorial/solvers/index.rst
Labels: documentation, PR no backport needed

#2585 Re-enable sdist publishing + clean up build workflows
  .github/workflows/build.yml
  continuous_integration/install_dependencies.sh
Labels: CI, PR backport needed

#2590 Fix artifact upload
  .github/workflows/build.yml
Labels: CI, PR backport needed

#2580 HiGHS solver interface for CVXPY
  cvxpy/__init__.py
  cvxpy/problems/problem.py
  cvxpy/reductions/solvers/conic_solvers/__init__.py
  cvxpy/reductions/solvers/conic_solvers/highs_conif.py
  cvxpy/reductions/solvers/defines.py
  cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
  cvxpy/settings.py
  cvxpy/tests/test_conic_solvers.py
  cvxpy/tests/test_qp_solvers.py
  doc/source/install/index.rst
  doc/source/tutorial/solvers/index.rst
  pyproject.toml
Labels: solver interfaces, PR no backport needed

#2564 new cumprod atom
  cvxpy/atoms/__init__.py
  cvxpy/atoms/affine/cumsum.py
  cvxpy/atoms/cumprod.py
  cvxpy/reductions/dgp2dcp/canonicalizers/__init__.py
  cvxpy/reductions/dgp2dcp/canonicalizers/cumprod_canon.py
  cvxpy/tests/test_atoms.py
  doc/source/api_reference/cvxpy.atoms.other_atoms.rst
  doc/source/tutorial/dgp/index.rst
Labels: PR no backport needed

#2577 CI: Build wheels for python 3.13
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/test_backends.yml
  continuous_integration/install_dependencies.sh
Labels: CI, PR no backport needed

#2592 Cleanup ``performance_test`` and ``test_benchmarks``
  continuous_integration/test_script.sh
  cvxpy/performance_tests/__init__.py
  cvxpy/performance_tests/test_param_cache.py
  cvxpy/performance_tests/test_robustness.py
  cvxpy/performance_tests/test_warmstart.py
  cvxpy/tests/test_benchmarks.py
  setup.py
Labels: PR no backport needed

#2589 DOC: changes for nd expressions (prep for 1.6)
  cvxpy/atoms/affine/index.py
  cvxpy/atoms/affine/sum.py
  cvxpy/expressions/leaf.py
  cvxpy/expressions/variable.py
Labels: documentation, PR no backport needed
