Repository cvxpy/cvxpy, pull requests merged in 2024-08, with the labels that each got.

#2525 adding warning for eventual change of default order
  cvxpy/atoms/affine/binary_operators.py
  cvxpy/atoms/affine/diag.py
  cvxpy/atoms/affine/hstack.py
  cvxpy/atoms/affine/index.py
  cvxpy/atoms/affine/reshape.py
  cvxpy/atoms/affine/upper_tri.py
  cvxpy/atoms/affine/vec.py
  cvxpy/atoms/elementwise/log_normcdf.py
  cvxpy/atoms/norm.py
  cvxpy/atoms/stats.py
  cvxpy/atoms/suppfunc.py
  cvxpy/atoms/total_variation.py
  cvxpy/constraints/finite_set.py
  cvxpy/constraints/power.py
  cvxpy/constraints/second_order.py
  cvxpy/expressions/expression.py
  cvxpy/reductions/complex2real/canonicalizers/abs_canon.py
  cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py
  cvxpy/reductions/complex2real/canonicalizers/soc_canon.py
  cvxpy/reductions/cone2cone/approximations.py
  cvxpy/reductions/cone2cone/exotic2common.py
  cvxpy/reductions/cone2cone/soc2psd.py
  cvxpy/reductions/cvx_attr2constr.py
  cvxpy/reductions/dcp2cone/canonicalizers/log_sum_exp_canon.py
  cvxpy/reductions/dcp2cone/canonicalizers/matrix_frac_canon.py
  cvxpy/reductions/dcp2cone/canonicalizers/perspective_canon.py
  cvxpy/reductions/dcp2cone/canonicalizers/pnorm_canon.py
  cvxpy/reductions/dcp2cone/canonicalizers/quad_over_lin_canon.py
  cvxpy/reductions/dcp2cone/canonicalizers/suppfunc_canon.py
  cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
  cvxpy/reductions/dgp2dcp/canonicalizers/add_canon.py
  cvxpy/reductions/dgp2dcp/canonicalizers/mulexpression_canon.py
  cvxpy/reductions/dgp2dcp/canonicalizers/pnorm_canon.py
  cvxpy/reductions/dgp2dcp/canonicalizers/sum_canon.py
  cvxpy/reductions/dgp2dcp/util.py
  cvxpy/reductions/discrete2mixedint/valinvec2mixedint.py
  cvxpy/reductions/eliminate_pwl/canonicalizers/dotsort_canon.py
  cvxpy/reductions/eliminate_pwl/canonicalizers/max_canon.py
  cvxpy/reductions/eliminate_pwl/canonicalizers/norm_inf_canon.py
  cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py
  cvxpy/reductions/solvers/conic_solvers/ecos_conif.py
  cvxpy/reductions/solvers/conic_solvers/scipy_conif.py
  cvxpy/reductions/solvers/conic_solvers/sdpa_conif.py
  cvxpy/reductions/utilities.py
  cvxpy/tests/solver_test_helpers.py
  cvxpy/tests/test_atoms.py
  cvxpy/tests/test_complex.py
  cvxpy/tests/test_constraints.py
  cvxpy/tests/test_derivative.py
  cvxpy/tests/test_expression_methods.py
  cvxpy/tests/test_grad.py
  cvxpy/tests/test_kron_canon.py
  cvxpy/tests/test_problem.py
  cvxpy/tests/test_qp_solvers.py
  cvxpy/tests/test_shape.py
  cvxpy/tests/test_suppfunc.py
  cvxpy/tests/test_valinvec2mixedint.py
  cvxpy/transforms/linearize.py
  cvxpy/utilities/perspective_utils.py
  cvxpy/utilities/power_tools.py
Labels: PR no backport needed

#2535 update nd-sum to be general for sparse variables
  cvxpy/lin_ops/canon_backend.py
  cvxpy/tests/test_expressions.py
Labels: PR no backport needed

#2523 Patch 1.5.3
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/test_backends.yml
  README.md
  continuous_integration/install_dependencies.sh
  cvxpy/atoms/affine/reshape.py
  cvxpy/atoms/condition_number.py
  cvxpy/atoms/gen_lambda_max.py
  cvxpy/atoms/lambda_max.py
  cvxpy/cvxcore/python/canonInterface.py
  cvxpy/expressions/leaf.py
  cvxpy/reductions/solvers/conic_solvers/conic_solver.py
  cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
  cvxpy/reductions/solvers/qp_solvers/xpress_qpif.py
  cvxpy/tests/test_conic_solvers.py
  doc/source/install/index.rst
  pyproject.toml
  sonar-project.properties
Labels: backport bugfix to 1.4 and 1.5

#2543 adding support for nd sum in parametrized expressions
  cvxpy/lin_ops/canon_backend.py
  cvxpy/tests/test_expressions.py
  cvxpy/tests/test_python_backends.py
Labels: PR no backport needed

#2527 Remove Python 2 compatibility code
  cvxpy/atoms/affine/affine_atom.py
  cvxpy/atoms/affine/binary_operators.py
  cvxpy/atoms/atom.py
  cvxpy/atoms/axis_atom.py
  cvxpy/atoms/elementwise/elementwise.py
  cvxpy/atoms/elementwise/kl_div.py
  cvxpy/atoms/elementwise/maximum.py
  cvxpy/atoms/elementwise/minimum.py
  cvxpy/atoms/elementwise/rel_entr.py
  cvxpy/atoms/perspective.py
  cvxpy/atoms/quad_form.py
  cvxpy/constraints/cones.py
  cvxpy/constraints/constraint.py
  cvxpy/expressions/expression.py
  cvxpy/expressions/leaf.py
  cvxpy/expressions/variable.py
  cvxpy/interface/base_matrix_interface.py
  cvxpy/performance_tests/test_warmstart.py
  cvxpy/problems/param_prob.py
  cvxpy/reductions/matrix_stuffing.py
  cvxpy/reductions/reduction.py
  cvxpy/reductions/solvers/conic_solvers/conic_solver.py
  cvxpy/reductions/solvers/solver.py
  cvxpy/tests/test_base_classes.py
  cvxpy/tests/test_cone2cone.py
  cvxpy/tests/test_examples.py
  cvxpy/tests/test_grad.py
  cvxpy/tests/test_matrices.py
  cvxpy/tests/test_problem.py
  cvxpy/tests/test_quad_form.py
  cvxpy/transforms/indicator.py
  cvxpy/utilities/canonical.py
  cvxpy/utilities/coeff_extractor.py
  cvxpy/utilities/key_utils.py
  examples/advanced/circuits.py
  examples/advanced/test.py
  examples/extensions/mixed_integer/noncvx_variable.py
Labels: PR no backport needed

#2479 Changing solver in tests from ECOS to CLARABEL
  cvxpy/tests/test_atoms.py
  cvxpy/tests/test_benchmarks.py
  cvxpy/tests/test_constraints.py
  cvxpy/tests/test_derivative.py
  cvxpy/tests/test_domain.py
  cvxpy/tests/test_dpp.py
  cvxpy/tests/test_dqcp.py
  cvxpy/tests/test_grad.py
  cvxpy/tests/test_monotonicity.py
  cvxpy/tests/test_nonlinear_atoms.py
  cvxpy/tests/test_perspective.py
  cvxpy/tests/test_problem.py
  cvxpy/tests/test_semidefinite_vars.py
Labels: PR no backport needed

#2541 Avoid unnecessarily creating numpy array of Var objects
  cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
Labels: PR backport needed
