Repository cvxpy/cvxpy, pull requests merged in 2025-06, with the labels that each got.

#2824 Fix typos across docs and comments
  cvxpy/expressions/leaf.py
  cvxpy/tests/test_python_backends.py
  doc/source/contributing/index.rst
  doc/source/examples/dqcp/hypersonic_shape_design.rst
  doc/source/examples/machine_learning/lasso_regression.rst
  doc/source/examples/machine_learning/ridge_regression.rst
  doc/source/tutorial/dpp/index.rst
  examples/machine_learning/lasso_regression.ipynb
  examples/machine_learning/ridge_regression.ipynb
  examples/notebooks/dqcp/hypersonic_shape_design.ipynb
Labels: codex

#2701 Finish ecos removal
  cvxpy/tests/test_constant_atoms.py
  cvxpy/tests/test_derivative.py
Labels: PR no backport needed

#2839 Only warns about `.value` for sparse leafs when it causes significant fillin
  cvxpy/expressions/leaf.py
  cvxpy/tests/test_attributes.py
Labels: PR backport needed, release-blocker

#2838 [HIGHS conif] Maps dual solution back to dual variables
  cvxpy/atoms/dotsort.py
  cvxpy/reductions/eliminate_pwl/canonicalizers/dotsort_canon.py
  cvxpy/reductions/qp2quad_form/canonicalizers/__init__.py
  cvxpy/reductions/solvers/conic_solvers/highs_conif.py
  cvxpy/reductions/solvers/solving_chain.py
  cvxpy/tests/test_conic_solvers.py
  cvxpy/tests/test_qp_solvers.py
Labels: PR backport needed, release-blocker
