Repository cvxpy/cvxpy, pull requests merged in 2025-07, with the labels that each got.

#2847 Doc improvements for some atoms, plus an Expression.cast function.
  cvxpy/atoms/quantum_cond_entr.py
  cvxpy/atoms/quantum_rel_entr.py
  cvxpy/atoms/von_neumann_entr.py
  cvxpy/constraints/exponential.py
  cvxpy/expressions/expression.py
  cvxpy/tests/test_quantum_rel_entr.py
  cvxpy/tests/test_von_neumann_entr.py
Labels: PR no backport needed, release-blocker

#2844 Adds SCS cuDSS, fixes a typo in the SCS docs, and adds CuClarabel install.
  doc/source/install/index.rst
  doc/source/tutorial/solvers/index.rst
Labels: documentation, PR no backport needed, release-blocker

#2823 DOC: prep for 1.7.0 release
  doc/source/api_reference/cvxpy.atoms.affine.rst
  doc/source/index.rst
  doc/source/install/index.rst
  doc/source/tutorial/constraints/index.rst
  doc/source/updates/index.rst
Labels: release-blocker

#2820 integrate cuOpt solver into cvxpy
  cvxpy/__init__.py
  cvxpy/reductions/solvers/conic_solvers/cuopt_conif.py
  cvxpy/reductions/solvers/defines.py
  cvxpy/settings.py
  cvxpy/tests/test_conic_solvers.py
  cvxpy/utilities/citations.py
  doc/source/install/index.rst
  doc/source/tutorial/solvers/index.rst
  pyproject.toml
Labels: solver interfaces, PR no backport needed, release-blocker
